### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by girs1982** [machinebox/sdk-go#22]
facetest.go:9:2: cannot find package "github.com/machinebox/sdk-go/facebox" in a                                 ny of:
        /usr/local/go/src/github.com/machinebox/sdk-go/facebox (from $GOROOT)
        /home/gansta/Downloads/detec/webcamFacebox/src/github.com/machinebox/sdk                                 -go/facebox (from $GOPATH)
facetest.go:10:2: cannot find package "github.com/matryer/is" in any of:
        /usr/local/go/src/github.com/matryer/is (from $GOROOT)
        /home/gansta/Downloads/detec/webcamFacebox/src/github.com/matryer/is (fr                                 om $GOPATH)

**Comment by dahernan** [comment]
Please have a look how to get dependencies in Go with go get:

`$ go get github.com/machinebox/sdk-go/facebox`

https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies

Thank you

**Comment by girs1982** [comment]
gansta@gansta-desktop:~$ go install -i facebox
can't load package: package facebox: cannot find package "facebox" in any of:
        /usr/local/go/src/facebox (from $GOROOT)
        /home/gansta/go/src/facebox (from $GOPATH)

**Comment by dahernan** [comment]
Sorry, to use the go-sdk, you need your Go environment, up and running as a prerequisite.
Please visit https://golang.org/ and follow the instructions for developing Go projects. I'm afraid we can not help you setting up the environment. Sorry about that

**Comment by girs1982** [comment]
maybe you will create instruction?, MY go lang work ND RUN APPs
