### ISSUE TITLE
cannot "go get" sdk-go

### ISSUE THREAD

**Issue by ederollora** [machinebox/sdk-go#24]
Running the command specified in the readme returns: 

```
~$ go get github.com/machinebox/sdk-go
can't load package: package github.com/machinebox/sdk-go: no Go files in $HOME/go/src/github.com/machinebox/sdk-go
```

Also, the app at https://github.com/machinebox/webFaceID imports boxutil but I get this error:
```
main.go:12:2: cannot find package "github.com/machinebox/sdk-go/x/boxutil" in any of:
	/usr/local/go/src/github.com/machinebox/sdk-go/x/boxutil (from $GOROOT)
	$HOME/go/src/github.com/machinebox/sdk-go/x/boxutil (from $GOPATH)
```
Can you give any light on this?

**Comment by ederollora** [comment]
Managed to solve the second issue regarding the sdk-go/x/boxutildirectory change but yesterday the `go get github.com/machinebox/sdk-go` command was working wrong.

**Comment by najamsk** [comment]
I am trying to get facebox work with some go code. follwing this tutorial.
https://blog.machinebox.io/introducing-web-face-id-how-to-use-html5-go-and-facebox-to-verify-your-face-b75cf2aee5e8

when i try to run go code it throws following error. 

```
main.go:12:2: cannot find package "github.com/machinebox/sdk-go/x/boxutil" in any of:
	/usr/local/go/src/github.com/machinebox/sdk-go/x/boxutil (from $GOROOT)
	/home/najam/go/src/github.com/machinebox/sdk-go/x/boxutil (from $GOPATH)
```
from above i understand its trying to get boxutil from some x folder but i cant find that x folder in hard drive. 
simple list command shows content of go-sdk 

```
→ ll                                                                [16ceff3]
total 60K
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 boxutil
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 classificationbox
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 facebox
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 fakebox
drwxr-xr-x 3 najam najam 4.0K فروری  25 10:13 internal
-rw-r--r-- 1 najam najam  12K فروری  25 10:13 LICENSE
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 nudebox
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 objectbox
-rw-r--r-- 1 najam najam  723 فروری  25 10:13 README.md
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 suggestionbox
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 tagbox
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 textbox
drwxr-xr-x 2 najam najam 4.0K فروری  25 10:13 videobox
```

**Comment by MarkxOBrian** [comment]
> Managed to solve the second issue regarding the **sdk-go/x/boxutil** directory change but yesterday the `go get github.com/machinebox/sdk-go` command was working wrong.

How did you solve? That's the only error am getting.

**Comment by dahernan** [comment]
`~$ go get -u github.com/machinebox/sdk-go` should work and is backwards compatible
