### ISSUE TITLE
Box is not ready, try again later

### ISSUE THREAD

**Issue by eqr** [machinebox/sdk-go#4]
I run machinebox in virtualized Ubuntu with Docker. Call to faceboxClient.Check ends with "facebox: faceClient call error: box is not ready, try again later" The result of /info endpoint call is 

```
{
	"success": true,
	"name": "facebox",
	"version": 1,
	"build": "7a1de89",
	"status": "ready"
}
```
What else shoud I check to find a reason?
Thanks in advance.

**Comment by dahernan** [comment]
Make sure that you assign around 4GB-6GB of memory to the docker container, lack of memory is the most common reason to not start. 
We should improve the message, but is difficult to forecast.
Feel free to re-open the issue if that doesn't work.
